"""initial_schema

Revision ID: 18a59065b30e
Revises: 
Create Date: 2026-06-05 03:34:02.700035
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18a59065b30e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('DELETE_POST', 'APPROVE_CLAIM', 'REJECT_CLAIM', 'MARK_RETURNED', 'BAN_USER', name='admin_action_type', create_constraint=True), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False, comment='ID of the affected item, claim, or user'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LOST', 'FOUND', name='item_type', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('ID_CARD', 'PHONE', 'BAG', 'BOOKS', 'KEYS', 'WALLET', 'ELECTRONICS', 'OTHERS', name='item_category', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('kept_at', sa.String(length=300), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'RETURNED', 'CLOSED', name='item_status', create_constraint=True), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_event_date'), 'items', ['event_date'], unique=False)
    op.create_index(op.f('ix_items_location'), 'items', ['location'], unique=False)
    op.create_index('ix_items_search_vector', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_type'), 'items', ['type'], unique=False)
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True, comment='Deep link to the relevant item or claim page'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('claimant_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('proof_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='claim_status', create_constraint=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'claimant_id', name='uq_claim_per_user_per_item')
    )
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_claims_item_id'), 'claims', ['item_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('item_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.create_table('verification_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('expected_answer', sa.String(length=500), nullable=False, comment='Private — only visible to the finder and admins'),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_questions_item_id'), 'verification_questions', ['item_id'], unique=False)
    op.create_table('claim_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['verification_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'question_id', name='uq_one_answer_per_question')
    )
    op.create_index(op.f('ix_claim_answers_claim_id'), 'claim_answers', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_answers_claim_id'), table_name='claim_answers')
    op.drop_table('claim_answers')
    op.drop_index(op.f('ix_verification_questions_item_id'), table_name='verification_questions')
    op.drop_table('verification_questions')
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_table('item_images')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_item_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_index(op.f('ix_items_type'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index('ix_items_search_vector', table_name='items', postgresql_using='gin')
    op.drop_index(op.f('ix_items_location'), table_name='items')
    op.drop_index(op.f('ix_items_event_date'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
